name = "motorcore-parts"
compatibility_date = "2026-08-20"

[assets]
directory = "."

[[d1_databases]]
binding = "DB"
database_name = "motorcore-parts-db"
database_id = "02c88b43-d8f8-43f9-ab1e-128a1c6a7a02"

