name = "motorcore-parts"
main = "_worker.js"
compatibility_date = "2024-09-23"

# Direct static asset routing
[assets]
directory = "."

# Binds your live D1 Database
[[d1_databases]]
binding = "DB"
database_name = "motorcore-parts-db"
database_id = "motorcore-parts-db"
